deployments:

  environmentMapping:

    development:

      - "dev*"

    testing:

      - "qa*"

      - "test*"

    staging:

      - "staging*"

      - "homolog*"

    production:

      - "prod*"

      - "production*"
